### ISSUE TITLE
License

### ISSUE THREAD

**Issue by TechnologyClassroom** [learnbyexample/command_help#1]
I am also a big fan of explainshell.  This looks like a useful tool.  CC BY-NC-SA is not a license for code and is not a free culture license.  Here is a link on the subject:

https://opensource.stackexchange.com/questions/1717/why-is-cc-by-sa-discouraged-for-code

I would suggest AGPL3.0 or MIT.  The traditional github way of licensing is to add a LICENSE.md file.  Github helps at that point with a pull down box with most of the common, free-culture licenses available.

**Comment by learnbyexample** [comment]
Thanks for the link
As per answers and comments, MIT has some of the same problems as CC
The major issue I see as of now is that using my code as part of another project that wants to use another license... I will do some more reading on this

**Comment by TechnologyClassroom** [comment]
MIT does not conflict with other licenses.  CC BY-NC-SA's NC clause does conflict with many licenses.

**Comment by learnbyexample** [comment]
but I do want NC or similar clause, I use it for all my repos... as per my understanding, MIT won't suit..

so, I will have to read up other licenses..

and if someone does use this code and having a specific issue due to this CC license, I will consider granting special permission..

**Comment by TechnologyClassroom** [comment]
Here are some links about the NC clause:
https://stallman.org/articles/online-education.html
https://wiki.creativecommons.org/wiki/NonCommercial

**Comment by learnbyexample** [comment]
decided to stick to CC for now
