### ISSUE TITLE
ch sed -i fails

### ISSUE THREAD

**Issue by SanketDG** [learnbyexample/command_help#3]
Doesnt show the description text

**Comment by learnbyexample** [comment]
yeah, that is known issue.. because for whatever reason, `man sed` has options and descriptions separated by blank line..

       --follow-symlinks

              follow symlinks when processing in place

       -i[SUFFIX], --in-place[=SUFFIX]

              edit files in place (makes backup if SUFFIX supplied)

       -l N, --line-length=N

              specify the desired line-wrap length for the `l' command

compare that to a sample from `man ls`

       -a, --all
              do not ignore entries starting with .

       -A, --almost-all
              do not list implied . and ..

       --author
              with -l, print the author of each file

I tried to handle both cases, but I wasn't getting it right.. it started breaking other working cases..

**Comment by learnbyexample** [comment]
added patch :)
